config/routes.rb
Rails.application.routes.draw do

  resources :song_requests, :only => [:index, :create, :new, :show] do
    member do
      put 'retry'
      get 'enqueue'
    end
  end

  get 'search_youtube_videos', controller: 'search_query', action: 'search_youtube_videos'
end

app/models/file_downloader.rb
class FileDownloader
  def self.enqueue_download song_url, song_request
    if File.exist? "songs/#{song_request.file_id}.m4a"
      song_request.status = 'Downloaded'
      if ENV['autopilot'] == 'true'
        song_request.enqueue!
      else
        song_request.save!
      end
    else
      Thread.new do
        %x{mkdir -p songs && youtube-dl -o songs/#{song_request.file_id}.%\\(ext\\)s -x #{song_url}}
        if File.exist? "songs/#{song_request.file_id}.m4a"
          song_request.status = 'Downloaded'
          if ENV['autopilot'] == 'true'
            song_request.enqueue!
          end
        else
          song_request.status = 'Error'
        end
        song_request.save!
      end.run
    end
  end
end

app/models/song_request.rb
class SongRequest < ActiveRecord::Base
  validates_presence_of :dedicated_to, :song_url, :message, :requestor
  validates_format_of :song_url, :with => /(http|https):\/\/www[.]youtube[.]com\/watch[?]v=.*/ix

  before_create :set_fields
  after_create :download_file
  default_scope { order ('id DESC') }
  
  def set_fields
    self.file_id = self.song_url.gsub(/http(s)?:\/\/www[.]youtube[.]com\//,"").gsub("/","_").gsub("watch?v=","").split("&").first
    description_text = %x{youtube-dl --get-title --get-description #{self.song_url}}
    if description_text.length > 255
      self.description = description_text[0..240] + "..."
    else
      self.description = description_text
    end
    self.status = 'New'
  end

  def download_file
    self.status = 'Enqueued'
    self.save!
    FileDownloader.enqueue_download(song_url, self)
  end

  def enqueue!
    self.status = 'Will be played'
    self.save!
    Resque.enqueue(PlaySong, self.id)
    Jukebox::Application.config.master_server_config['other_players'].each do | player_name |
      Resque.enqueue_to(player_name, PlaySongPlayer, self.id)
    end if Jukebox::Application.config.master_server_config['other_players'].present?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/search_query_controller.rb
require 'net/http'
require 'json'

class SearchQueryController < ApplicationController
  def search_youtube_videos
    results = get_search_query_response(CGI.escape(params[:q]))
    render :json => results
  end

  private 
  def get_search_query_response query
    uri = URI.parse("https://www.youtube.com/results?search_query=#{query}&spf=navigate")
    response = JSON.parse(Net::HTTP.get(uri))
    body_part = response.last["body"]
    search_results = body_part["content"].scan(/\<h3.*?\<a href.*?\<\/h3\>/)
    search_results.collect {|a| { name: a.match(/title=".*?"/)[0].gsub("title=","").gsub("\"",""), url: a.match(/href="\/.*?"/)[0].gsub("href=","").gsub("\"","") }}
  end
end

app/controllers/song_requests_controller.rb
class SongRequestsController < ApplicationController
  before_action :set_song_request, only: [:retry, :enqueue, :show]

  def index
    @song_requests = SongRequest.all
  end

  def new
    @song_request = SongRequest.new
  end

  def show
  end

  def retry
    @song_request.download_file
    redirect_to action: :index
  end

  def create
    @song_request = SongRequest.new(song_request_params)

    respond_to do |format|
      if @song_request.save
        format.html { redirect_to action: :index }
        format.json { render :show, status: :created, location: @song_request }
      else
        format.html { render :new }
        format.json { render json: @song_request.errors, status: :unprocessable_entity }
      end
    end
  end

  def enqueue
    render json: {error: "wrong secret"} and return if params[:admin_secret] != Jukebox::Application.config.admin_secret
    @song_request.enqueue!
    render json: {status: @song_request.status, id: @song_request.id}
  end

  private
    def set_song_request
      @song_request = SongRequest.find(params[:id])
    end

    def song_request_params
      params.require(:song_request).permit(:dedicated_to, :song_url, :message, :requestor)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/search_query_helper.rb
module SearchQueryHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Jukebox</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/song_requests/_form.html.erb
<%= form_for(@song_request) do |f| %>
  <% if @song_request.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@song_request.errors.count, "error") %> prohibited this song_request from being saved:</h2>

      <ul>
      <% @song_request.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<table width="100%">
  <tr>
    <td>
      <div class="field">
        <%= f.label :dedicated_to %><br>
        <%= f.text_field :dedicated_to %>
      </div>
    </td>
    <td>
      <div class="field">
        <%= f.label :song_url %><br>
        <%= f.text_field :song_url %>
      </div>
    </td>
  </tr>
  <tr>
    <td>
      <div class="field">
        <%= f.label :message %><br>
        <%= f.text_area :message %>
      </div>
    </td>
    <td>
      <div class="field">
        <%= f.label :requestor %><br>
        <%= f.text_field :requestor %>
      </div>
    </td>
  </tr>
</table>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/song_requests/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Song Requests</h1>

<table width = "100%" BORDER=1 CELLPADDING=3 CELLSPACING=1 
    RULES=ROWS FRAME=BOX>
  <thead>
    <tr>
      <th>Dedicated to</th>
      <th>URL (youtube.com)</th>
      <th width="30%">Youtube Song Description</th>
      <th>Message</th>
      <th>Requestor</th>
      <th>State</th>
    </tr>
  </thead>

  <tbody>
    <% admin_secret_present = params[Jukebox::Application.config.admin_secret].present? %>
    <% @song_requests.each do |song_request| %>
      <tr align="center">
        <td><%= song_request.dedicated_to %></td>
        <td><%= song_request.song_url.gsub(/http(s)?:\/\/[w]*?[.]youtube[.]com/,"").split('&').first %></td>
        <td><%= song_request.description ? song_request.description.gsub("\n","<br>").html_safe : "" %></td>
        <td><%= song_request.message %></td>
        <td><%= song_request.requestor %></td>
        <td><%= song_request.status %><% if song_request.status == "Error" || admin_secret_present %>
          <br/><%= link_to 'Retry', retry_song_request_path(song_request), method: :put%>
        <%end%>
        <% if admin_secret_present && !%w(Error Enqueued).include?(song_request.status) %>
          <%= link_to 'Enqueue', enqueue_song_request_path(song_request, admin_secret: Jukebox::Application.config.admin_secret), target: :new%>
        <% end %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Song request', new_song_request_path %>

app/views/song_requests/new.html.erb
<h2>New Song Request</h2>
<p>Only youtube urls are supported.</p>
<%= render 'form' %>

<%= link_to 'Back', song_requests_path %>

<br/><br/><br/><br/>
<input type="text" placeholder="Search for youtube videos..." id="youtube_url_fetcher" title="Type and press enter, then click on one result to populate the url" />
<div id="search_results"></div>